sudo: false
addons:
    apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
           - gcc-5
           - g++-5
language: julia
julia:
  - 0.5
os:
  - linux
  - osx
env:
  - GROUP=AutoTest
  - GROUP=Bench
matrix:
    fast_finish: true
    exclude:
       - os: osx
         env: GROUP=Bench
    allow_failures:
       - env: GROUP=AutoTest
         os: osx
       - env: GROUP=Bench

notifications:
    email: false
script:
  - if [ "$(uname)" != "Darwin" ]; then ln -s `which gcc-5` gcc && export PATH=`pwd`:$PATH && echo $PATH; fi
  - gcc -v
  - wget https://github.com/stan-dev/cmdstan/releases/download/v2.14.0/cmdstan-2.14.0.zip
  - unzip cmdstan-2.14.0.zip -d cmdstan
  - echo "CMDSTAN_HOME = `pwd`/cmdstan" >> ~/.juliarc.jl
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.update();
             Pkg.clone(pwd(), "Turing");
             Pkg.build("Turing");
             if ENV["GROUP"] != "Bench"
                Pkg.test("Turing"; coverage=true)
             else
                Pkg.add("Stan"); Pkg.build("Stan");
                include(Pkg.dir("Turing")*"/benchmarks/benchmark.jl")
             end'
after_success:
  - julia -e 'if ENV["GROUP"] != "Bench"
                cd(Pkg.dir("Turing")); Pkg.add("Coverage");
                using Coverage; Coveralls.submit(process_folder())
                end'
notifications:
    email: false
