language: julia
os:
  - linux
    addons:
        apt:
          packages:
            - gcc-5
            - g++-5
  - osx
julia:
  - 0.5
notifications:
    email: false
script:
  - gcc -v
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Turing"); Pkg.test("Turing"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Turing")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
