sudo: false
addons:
    apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
           - gcc-5
           - g++-5  
language: julia
julia: 
  - 0.5
os:
  - linux
  - osx
env:
  - TEST_GROUP=F
matrix:
    fast_finish: true
    allow_failures:
       - env: TEST_GROUP=F
         os: osx
  
notifications:
    email: false
script:
  - if [ "$(uname)" != "Darwin" ]; then ln -s `which gcc-5` gcc && export PATH=`pwd`:$PATH && echo $PATH; fi
  - gcc -v
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.update(); 
             Pkg.clone(pwd(), "Turing");  
             Pkg.build("Turing"); 
             Pkg.test("Turing"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Turing")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
notifications:
    email: false
