sudo: false
addons:
    apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
           - gcc-5
           - g++-5  
matrix:
    include:
       - language: julia
         julia: 0.5
         os: linux
       - language: julia
         julia: 0.5
         os: osx

notifications:
    email: false
script:
  - ln -s `which gcc-5` gcc && export PATH=`pwd`:$PATH && echo $PATH
  - gcc -v
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Turing"); Pkg.test("Turing"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Turing")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
notifications:
    email: false
